server:
  port: 12345                           # 端口
  servlet:
    context-path: /webhook              # 接口前缀

# webhook
webhook:
  ip:                                     # IP 白名单
    whitelist:
      enabled: 0                          # 是否启用 IP 白名单（0：禁用；1：启用）
      content: localhost,127.0.0.1        # IP 白名单
  secret:                                 # webhook 密钥
    enabled: 1                            # 是否启用 webhook 密钥（0：禁用；1：启用）
    content: 666666                       # webhook 密钥，防止接口被盗用
  script:                                 # 脚本路径及脚本名称列表
    path: /home/admin/scripts/            # 脚本路径
    names: webhook_java,webhook_vue       # 脚本名称列表，即 webhook_java.sh, b.sh, c.sh
  file:                                   # 文件
    path: /home/admin/file                # 文件存储路径